[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ETOgaosion"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/BlueSpaceXID"

[social.params]
icon = "brand-twitter"