mainSections = ["post", "about"]

[google]
verificationNumber = "yX3maE6pmP1DkoWbMi0nHg7gSXTKWqs5OPgtrfVy2eA"

[footer]
since = 2023

[sidebar]
compact = false
doctor = "蓝色空间 #4686"
level = 112
subtitle = "<b>CSer in ICT</b> <br /> <b>Research Direction</b>: OS, Cloud, Virtualization<br /><b>Hobbies</b>: Game, Music, Movies, Tech, Photograph, Travel"

  [sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.jpeg"
